### ISSUE TITLE
k_max

### ISSUE THREAD

**Issue by miladinovic** [inuritdino/HiguchiFractalDimension#2]
Hi,

Thank for the very efficient and nice code. However, k_max as input feature is missing (also described in the Higuchi's original paper from '88).

Looking at your code I was wondering how do you select k_max, which is usually given as an input?

**Comment by inuritdino** [comment]
Hi and thanks for your interest!

The array of `k`'s is generated by the call:
```
k = np.logspace(start=np.log2(2),stop=np.log2(size//2),base=2,num=num_val,dtype=np.int)
```

So, it is an evenly spaced array (in log scale) starting from 2 and ending with half of the full length of the series (i.e. size//2). In other words, it starts from the *min* up to the *max* possible value for `k`. Since for `k=1` it is the original time series only, and for `k>size//2` it is a lot of time "series" of 1 point in length and `Lkm` is not defined. So, the two limit cases are selected for the `k` array generation. This is a bit of an overshoot maybe...

An obvious drawback of this approach is that one might perhaps not want to compute  `Lkm` for such large `k`'s due to limited resources. But otherwise, if lower `k_max` is needed, one could simply truncate the output array of  `Lk` and `k`'s.

However, the above call also defines the parameter `num_val` i.e. number of `k` values to generate between the min and max limits. This was not available to the user. I have just added this feature and now one can use an option to `hfd` function: `num_k` (default is 50).

Please, tell me if you see my point. Could you also tell me why would you need such `k_max` manually defined? Maybe I could get a bit more insight based on a specific application.

Thank you in advance!

**Comment by inuritdino** [comment]
Hi,

I have added the option `k_max` to the main functions... 

Kindly refer to <https://github.com/inuritdino/HiguchiFractalDimension/commit/ce98c1dfb26ecf6599d5b8af4ba10cb328cd8cc2> 

Hereby, I close the issue.

Thanks again!
